# Generated by Django 4.0.1 on 2022-01-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
