# Generated by Django 4.0.1 on 2022-01-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_tweet_date_alter_tweet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
