# Generated by Django 4.0.1 on 2022-01-28 23:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_alter_tweet_date_alter_tweet_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='message',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='sentiment_score',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='time',
        ),
        migrations.AddField(
            model_name='tweet',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=[], size=None),
            preserve_default=False,
        ),
    ]
