# Generated by Django 4.0.1 on 2022-01-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=5)),
                ('day_low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('day_high', models.DecimalField(decimal_places=2, max_digits=8)),
                ('day_close', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
